Repository hashicorp/terraform-plugin-testing, pull requests merged in 2023-08, with the labels that each got.

#164 helper/resource: Remove data source and resource `id` attribute requirement
  .changes/unreleased/ENHANCEMENTS-20230820-195300.yaml
  .changes/unreleased/FEATURES-20230820-195624.yaml
  helper/resource/state_shim.go
  helper/resource/testcase_test.go
  helper/resource/testing.go
  helper/resource/testing_new_import_state.go
  helper/resource/teststep_test.go
  internal/testing/testsdk/providerserver/providerserver.go
Labels: enhancement

#169 website: Update GitHub Actions example for setup-go@v4 and using go.mod version
  website/docs/plugin/testing/acceptance-tests/index.mdx
Labels: documentation

#177 Fix regression by allowing providers defined at `TestCase` level with providers defined within `TestStep.Config`
  .changes/unreleased/BUG FIXES-20230831-171932.yaml
  helper/resource/teststep_validate.go
  helper/resource/teststep_validate_test.go
Labels: bug
