Repository hashicorp/terraform-plugin-testing, pull requests merged in 2023-11, with the labels that each got.

#211 Fix typo in documentation for `-sweep-allow-failures` flag
  helper/resource/testing.go
Labels: documentation

#228 Skip tests when resource unavailable or entire resource is marked unknown
  plancheck/expect_null_output_value_at_path_test.go
  plancheck/expect_unknown_output_value_at_path_test.go
  plancheck/expect_unknown_output_value_test.go
Labels: bug

#223 helper/resource: Refresh during plan rather than separately and remove state shimming when possible
  .changes/unreleased/ENHANCEMENTS-20231122-115402.yaml
  helper/resource/testing_new_config.go
  internal/plugintest/working_dir.go
Labels: enhancement

#229 tfversion: Add variables for version 1.6.0 and 1.7.0
  tfversion/versions.go
Labels: enhancement

#216 Add terraform block to config when not already present
  .changes/unreleased/ENHANCEMENTS-20231130-092645.yaml
  helper/resource/testcase_providers_test.go
  helper/resource/testing_new.go
  helper/resource/testing_new_config.go
  helper/resource/testing_test.go
  helper/resource/teststep_providers.go
  helper/resource/teststep_providers_test.go
  internal/testing/testprovider/provider_protov5.go
  internal/testing/testsdk/provider/provider_protov5.go
  internal/testing/testsdk/providerserver/providerserver_protov5.go
  tfversion/all_test.go
  tfversion/any_test.go
  tfversion/require_above_test.go
  tfversion/require_not_test.go
  tfversion/skip_below_test.go
  tfversion/skip_between_test.go
  tfversion/skip_if_test.go
Labels: enhancement
