Repository hashicorp/terraform-plugin-testing, pull requests merged in 2024-03, with the labels that each got.

#300 Bump Go version to 1.21
  .changes/unreleased/NOTES-20240305-111036.yaml
  .github/workflows/ci-go.yml
  README.md
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: dependencies

#304 tfversion: Add variable for version 1.9.0
  tfversion/versions.go
Labels: enhancement

#305 Update `RandIpAddress()` so it can use any prefix as input
  .changes/unreleased/ENHANCEMENTS-20240315-185051.yaml
  helper/acctest/random.go
  helper/acctest/random_test.go
Labels: bug

#314 helper/resource: Fix panic in output state shimming when a tuple is present
  .changes/unreleased/BUG FIXES-20240325-125136.yaml
  helper/resource/state_shim.go
  helper/resource/state_shim_test.go
  helper/resource/testing_new_test.go
Labels: bug

#313 knownvalue: Add `TupleExact`, `TuplePartial` and `TupleSizeExact` checks for dynamic value testing
  .changes/unreleased/ENHANCEMENTS-20240325-120539.yaml
  knownvalue/list_partial_test.go
  knownvalue/tuple.go
  knownvalue/tuple_partial.go
  knownvalue/tuple_partial_test.go
  knownvalue/tuple_size.go
  knownvalue/tuple_size_test.go
  knownvalue/tuple_test.go
  website/data/plugin-testing-nav-data.json
  website/docs/plugin/testing/acceptance-tests/known-value-checks/custom.mdx
  website/docs/plugin/testing/acceptance-tests/known-value-checks/index.mdx
  website/docs/plugin/testing/acceptance-tests/known-value-checks/tuple.mdx
Labels: enhancement

#316 tfversion: Treat Terraform CLI prerelease versions as equal to patch versions in SkipBelow
  .changes/unreleased/ENHANCEMENTS-20240327-171628.yaml
  tfversion/skip_below.go
  tfversion/skip_below_test.go
Labels: enhancement

#317 tfversion: Finish prerelease version semantic equality handling
  .changes/unreleased/BUG FIXES-20240328-180800.yaml
  .changes/unreleased/ENHANCEMENTS-20240327-171628.yaml
  tfversion/require_above.go
  tfversion/require_above_test.go
  tfversion/require_below.go
  tfversion/require_below_test.go
  tfversion/require_between.go
  tfversion/require_between_test.go
  tfversion/require_not.go
  tfversion/require_not_test.go
  tfversion/skip_above.go
  tfversion/skip_above_test.go
  tfversion/skip_below.go
  tfversion/skip_below_test.go
  tfversion/skip_between.go
  tfversion/skip_between_test.go
  tfversion/skip_if.go
  tfversion/skip_if_test.go
  website/docs/plugin/testing/acceptance-tests/tfversion-checks.mdx
Labels: enhancement
