Repository hashicorp/terraform-plugin-testing, pull requests merged in 2024-01, with the labels that each got.

#261 website: Mention PlanOnly to ConfigPlanChecks in migration guide
  website/docs/plugin/testing/migrating.mdx
Labels: documentation

#265 Modify regex to detect other legitimate forms of provider block declaration
  .changes/unreleased/BUG FIXES-20240108-154019.yaml
  .changes/unreleased/BUG FIXES-20240108-170824.yaml
  internal/teststep/config.go
  internal/teststep/directory_test.go
  internal/teststep/file_test.go
  internal/teststep/string_test.go
  internal/teststep/testdata/provider_block_quoted_with_attributes_no_spaces/main.tf
  internal/teststep/testdata/provider_block_quoted_without_attributes_no_spaces/main.tf
  internal/teststep/testdata/provider_block_unquoted_with_attributes_no_trailing_space/main.tf
  internal/teststep/testdata/provider_block_unquoted_without_attributes_no_trailing_space/main.tf
  internal/teststep/testdata/terraform_block_no_space/main.tf
Labels: bug

#278 tfversion: Add variable for version 1.8.0
  tfversion/versions.go
Labels: enhancement
