Repository hashicorp/terraform-plugin-testing, pull requests merged in 2025-03, with the labels that each got.

#412 proposal: function checks
  .changes/unreleased/FEATURES-20250120-155954.yaml
  knownvalue/bool_func.go
  knownvalue/bool_func_test.go
  knownvalue/float32_func.go
  knownvalue/float32_func_test.go
  knownvalue/float64_func.go
  knownvalue/float64_func_test.go
  knownvalue/int32_func.go
  knownvalue/int32_func_test.go
  knownvalue/int64_func.go
  knownvalue/int64_func_test.go
  knownvalue/number_func.go
  knownvalue/number_func_test.go
  knownvalue/string_func.go
  knownvalue/string_func_test.go
  website/docs/plugin/testing/acceptance-tests/known-value-checks/bool.mdx
  website/docs/plugin/testing/acceptance-tests/known-value-checks/float32.mdx
  website/docs/plugin/testing/acceptance-tests/known-value-checks/float64.mdx
  website/docs/plugin/testing/acceptance-tests/known-value-checks/int32.mdx
  website/docs/plugin/testing/acceptance-tests/known-value-checks/int64.mdx
  website/docs/plugin/testing/acceptance-tests/known-value-checks/number.mdx
  website/docs/plugin/testing/acceptance-tests/known-value-checks/string.mdx
Labels: enhancement

#454 chore: Update minimum Go version in module
  .changes/unreleased/NOTES-20250317-082825.yaml
  .github/workflows/ci-go.yml
  README.md
  go.mod
  go.sum
  tools/go.mod
  tools/go.sum
Labels: dependencies

#455 Add the missing/extra attribute names to the error message for `knownvalue.ObjectExact`
  .changes/unreleased/ENHANCEMENTS-20250317-182730.yaml
  knownvalue/object.go
  knownvalue/object_test.go
Labels: enhancement

#458 chore: Add `prerelease: auto` for future pre-releases
  .goreleaser.yml
Labels: github_actions

#468 Add `statecheck.ExpectIdentityValue` for asserting resource identity values
  .changes/unreleased/NOTES-20250325-115927.yaml
  .changes/unreleased/upcoming-stable/ENHANCEMENTS-20250325-121007.yaml
  .copywrite.hcl
  go.mod
  go.sum
  internal/testing/testprovider/resource.go
  internal/testing/testsdk/providerserver/providerserver.go
  internal/testing/testsdk/providerserver/tftypes.go
  internal/testing/testsdk/resource/resource.go
  statecheck/expect_identity_value.go
  statecheck/expect_identity_value_example_test.go
  statecheck/expect_identity_value_test.go
  tfversion/versions.go
Labels: enhancement
